export const ENV_KEYS = {
  port: 'PORT',
  apiPort: 'API_PORT',
  supabaseUrl: 'SUPABASE_URL',
  supabaseAnonKey: 'SUPABASE_ANON_KEY',
  supabaseServiceRoleKey: 'SUPABASE_SERVICE_ROLE_KEY',
  databaseUrl: 'DATABASE_URL',
  directUrl: 'DIRECT_URL',
  marketDataProvider: 'MARKET_DATA_PROVIDER',
  marketDataApiKey: 'MARKET_DATA_API_KEY',
  newsDataProvider: 'NEWS_DATA_PROVIDER',
  newsDataApiKey: 'NEWS_DATA_API_KEY',
  fmpApiKey: 'FMP_API_KEY',
  newsApiKey: 'NEWSAPI_KEY',
  gnewsApiKey: 'GNEWS_API_KEY',
  allowMockFallback: 'ALLOW_MOCK_FALLBACK',
  akshareBaseUrl: 'AKSHARE_BASE_URL',
  aiPrimaryBaseUrl: 'AI_PRIMARY_BASE_URL',
  aiPrimaryModel: 'AI_PRIMARY_MODEL',
  aiPrimaryApiKey: 'AI_PRIMARY_API_KEY',
  aiFallbackBaseUrl: 'AI_FALLBACK_BASE_URL',
  aiFallbackModel: 'AI_FALLBACK_MODEL',
  aiFallbackApiKey: 'AI_FALLBACK_API_KEY',
} as const;
